import { LineEdit, Button, TextEdit } from "std-widgets.slint";

export component AppWindow inherits Window {
    in property <string> data-out: "";

    callback is_correct(string);
    callback probar_codigo(string);

    min-width: 700px;
    preferred-width: self.min-width;
    max-width: 1920px;

    min-height: 900px;
    preferred-height: self.min-height;
    max-height: 1080px;

    GridLayout {
        spacing-vertical: 20px;
        padding-left: parent.width * 0.1;
        padding-right: parent.width * 0.1;

        Row {
            Text {
                text: "Expresion regular: \n[A-Za-z]\\.[a-z$!?_]*";
                font-size: 20px;
                font-weight: 750;
                horizontal-alignment: center;
                vertical-alignment: center;
                max-height: 60px;
            }
        }

        Row {
            VerticalLayout {
                max-height: 80px;

                Text {
                    text: "Expresion: ";
                    font-size: 15px;
                    font-weight: 500;
                    horizontal-alignment: left;
                }

                Rectangle {
                    background: green;
                    border-color: yellowgreen;
                    border-radius: 4px;
                    width: root.width * 0.8;
                    height: 60px;

                    input := LineEdit {
                        placeholder-text: "s.ejemplo";
                        width: parent.width;
                        height: parent.height;
                    }
                }
            }
        }

        Row {
            VerticalLayout {
                max-height: 80px;
                
                Text {
                    text: "Resultado (Expresion): ";
                    font-size: 15px;
                    font-weight: 500;
                    horizontal-alignment: left;
                }

                Rectangle {
                    background: rebeccapurple;
                    border-color: blueviolet;
                    border-radius: 4px;
                    width: root.width * 0.8;
                    height: 60px;

                    output := Text {
                        text: root.data-out;
                        font-size: 15px;
                        font-weight: 500;
                        width: parent.width * 0.9;
                        vertical-alignment: center;
                        horizontal-alignment: left;
                    }
                }
            }
        }

        Row {
            Rectangle {
                background: black;
                border-color: yellow;
                border-radius: 4px;
                width: root.width * 0.8;
                height: 60px;

                Button {
                    text: "Checar expresion";
                    width: parent.width * 0.97;
                    height: parent.height * 0.8;
                    clicked => { 
                        // Validate expression input
                        is_correct(input.text);
                    }  
                }
            }
        }

        Row {
            VerticalLayout {
                max-height: 200px;

                Text {
                    text: "Codigo de entrada: ";
                    font-size: 15px;
                    font-weight: 500;
                    horizontal-alignment: left;
                }

                Rectangle {
                    background: black;
                    border-color: gray;
                    border-radius: 4px;
                    width: root.width * 0.8;
                    height: 400px;

                    code_input := TextEdit {
                        placeholder-text: "Escribir codigo...";
                        width: parent.width;
                        height: parent.height;
                    }
                }
            }
        }

        Row {
            Rectangle {
                background: black;
                border-color: yellow;
                border-radius: 4px;
                width: root.width * 0.8;
                height: 60px;

                Button {
                    text: "Probar codigo";
                    width: parent.width * 0.97;
                    height: parent.height * 0.8;
                    clicked => { 
                        probar_codigo(code_input.text);
                    }
                }
            }
        }

        Row {}
    }
}
